export const PHRASEBOOK: Record<string, Record<string, string>> = {
    'hello': {
        fr: 'Bonjour', es: 'Hola', de: 'Hallo',
        hi: 'नमस्ते', 'zh-CN': '你好', ja: 'こんにちは',
        ko: '안녕하세요', ru: 'Привет', ar: 'مرحبا',
        pt: 'Olá', it: 'Ciao', bn: 'হ্যালো',
        te: 'హలో', mr: 'नमस्कार', ta: 'ஹலோ',
        ur: 'ہیلو', ml: 'ഹലോ', kn: 'ಹಲೋ',
        pa: 'ਹੈਲੋ', vi: 'Xin chào',
    },
    'hi': {
        fr: 'Salut', es: 'Hola', de: 'Hi',
        hi: 'हाय', zh: '嗨', ja: 'やあ',
        ko: '안녕', ru: 'Привет', ar: 'أهلاً',
        pt: 'Oi', it: 'Ciao', bn: 'হাই',
        te: 'హాయ్', mr: 'हाय', ta: 'ஹாய்',
        ur: 'ہائے', ml: 'ഹായ്', kn: 'ಹಾಯ್',
        pa: 'ਹਾਏ', vi: 'Chào',
    },
    'goodbye': {
        fr: 'Au revoir', es: 'Adiós', de: 'Auf Wiedersehen',
        hi: 'अलविदा', zh: '再见', ja: 'さようなら',
        ko: '안녕히 가세요', ru: 'До свидания', ar: 'مع السلامة',
        pt: 'Adeus', it: 'Arrivederci', bn: 'বিদায়',
        te: 'వీడ్కోలు', mr: 'निरोप', ta: 'விடை',
        ur: 'خدا حافظ', ml: 'വിട', kn: 'ವಿದಾಯ',
        pa: 'ਵਿਦਾ', vi: 'Tạm biệt',
    },
    'bye': {
        fr: 'Au revoir', es: 'Adiós', de: 'Tschüss',
        hi: 'अलविदा', zh: '拜拜', ja: 'バイバイ',
        ko: '잘 가', ru: 'Пока', ar: 'وداعاً',
        pt: 'Tchau', it: 'Ciao', bn: 'বাই',
        te: 'బై', mr: 'बाय', ta: 'பை',
        ur: 'بائے', ml: 'ബൈ', kn: 'ಬೈ',
        pa: 'ਬਾਏ', vi: 'Bye',
    },
    'good morning': {
        fr: 'Bonjour', es: 'Buenos días', de: 'Guten Morgen',
        hi: 'सुप्रभात', zh: '早上好', ja: 'おはようございます',
        ko: '좋은 아침이에요', ru: 'Доброе утро', ar: 'صباح الخير',
        pt: 'Bom dia', it: 'Buongiorno', bn: 'শুভ সকাল',
        te: 'శుభోదయం', mr: 'सुप्रभात', ta: 'காலை வணக்கம்',
        ur: 'صبح بخیر', ml: 'സുപ്രഭാതം', kn: 'ಶುಭೋದಯ',
        pa: 'ਸ਼ੁਭ ਸਵੇਰ', vi: 'Chào buổi sáng',
    },
    'good night': {
        fr: 'Bonne nuit', es: 'Buenas noches', de: 'Gute Nacht',
        hi: 'शुभ रात्रि', zh: '晚安', ja: 'おやすみなさい',
        ko: '좋은 밤 되세요', ru: 'Спокойной ночи', ar: 'تصبح على خير',
        pt: 'Boa noite', it: 'Buonanotte', bn: 'শুভ রাত্রি',
        te: 'శుభ రాత్రి', mr: 'शुभ रात्री', ta: 'இனிய இரவு',
        ur: 'شب بخیر', ml: 'ശുഭ രാത്രി', kn: 'ಶುಭ ರಾತ್ರಿ',
        pa: 'ਸ਼ੁਭ ਰਾਤ', vi: 'Chúc ngủ ngon',
    },
    'thank you': {
        fr: 'Merci', es: 'Gracias', de: 'Danke',
        hi: 'धन्यवाद', zh: '谢谢', ja: 'ありがとうございます',
        ko: '감사합니다', ru: 'Спасибо', ar: 'شكراً',
        pt: 'Obrigado', it: 'Grazie', bn: 'ধন্যবাদ',
        te: 'ధన్యవాదాలు', mr: 'धन्यवाद', ta: 'நன்றி',
        ur: 'شکریہ', ml: 'നന്ദി', kn: 'ಧನ್ಯವಾದ',
        pa: 'ਧੰਨਵਾਦ', vi: 'Cảm ơn',
    },
    'thanks': {
        fr: 'Merci', es: 'Gracias', de: 'Danke',
        hi: 'शुक्रिया', zh: '谢谢', ja: 'ありがとう',
        ko: '고마워요', ru: 'Спасибо', ar: 'شكراً',
        pt: 'Obrigado', it: 'Grazie', bn: 'ধন্যবাদ',
        te: 'థాంక్స్', mr: 'आभारी', ta: 'நன்றி',
        ur: 'شکریہ', ml: 'നന്ദി', kn: 'ಧನ್ಯವಾದ',
        pa: 'ਧੰਨਵਾਦ', vi: 'Cảm ơn',
    },
    'please': {
        fr: "S'il vous plaît", es: 'Por favor', de: 'Bitte',
        hi: 'कृपया', zh: '请', ja: 'お願いします',
        ko: '제발', ru: 'Пожалуйста', ar: 'من فضلك',
        pt: 'Por favor', it: 'Per favore', bn: 'দয়া করে',
        te: 'దయచేసి', mr: 'कृपया', ta: 'தயவுசெய்து',
        ur: 'براہ کرم', ml: 'ദയവായി', kn: 'ದಯವಿಟ್ಟು',
        pa: 'ਕਿਰਪਾ ਕਰਕੇ', vi: 'Làm ơn',
    },
    'sorry': {
        fr: 'Désolé', es: 'Lo siento', de: 'Entschuldigung',
        hi: 'माफ़ करें', zh: '对不起', ja: 'すみません',
        ko: '죄송합니다', ru: 'Извините', ar: 'آسف',
        pt: 'Desculpe', it: 'Scusa', bn: 'দুঃখিত',
        te: 'క్షమించండి', mr: 'क्षमा करा', ta: 'மன்னிக்கவும்',
        ur: 'معاف کریں', ml: 'ക്ഷമിക്കൂ', kn: 'ಕ್ಷಮಿಸಿ',
        pa: 'ਮਾਫ਼ ਕਰਨਾ', vi: 'Xin lỗi',
    },
    'yes': {
        fr: 'Oui', es: 'Sí', de: 'Ja',
        hi: 'हाँ', zh: '是', ja: 'はい',
        ko: '네', ru: 'Да', ar: 'نعم',
        pt: 'Sim', it: 'Sì', bn: 'হ্যাঁ',
        te: 'అవును', mr: 'हो', ta: 'ஆம்',
        ur: 'ہاں', ml: 'അതെ', kn: 'ಹೌದು',
        pa: 'ਹਾਂ', vi: 'Có',
    },
    'no': {
        fr: 'Non', es: 'No', de: 'Nein',
        hi: 'नहीं', zh: '不', ja: 'いいえ',
        ko: '아니요', ru: 'Нет', ar: 'لا',
        pt: 'Não', it: 'No', bn: 'না',
        te: 'లేదు', mr: 'नाही', ta: 'இல்லை',
        ur: 'نہیں', ml: 'ഇല്ല', kn: 'ಇಲ್ಲ',
        pa: 'ਨਹੀਂ', vi: 'Không',
    },
    'i love you': {
        fr: "Je t'aime", es: 'Te amo', de: 'Ich liebe dich',
        hi: 'मैं तुमसे प्यार करता हूँ', zh: '我爱你', ja: '愛しています',
        ko: '사랑해요', ru: 'Я тебя люблю', ar: 'أنا أحبك',
        pt: 'Eu te amo', it: 'Ti amo', bn: 'আমি তোমাকে ভালোবাসি',
        te: 'నేను నిన్ను ప్రేమిస్తున్నాను', mr: 'मी तुझ्यावर प्रेम करतो',
        ta: 'நான் உன்னை நேசிக்கிறேன்', ur: 'میں تم سے محبت کرتا ہوں',
        ml: 'ഞാൻ നിന്നെ സ്നേഹിക്കുന്നു', kn: 'ನಾನು ನಿನ್ನನ್ನು ಪ್ರೀತಿಸುತ್ತೇನೆ',
        pa: 'ਮੈਂ ਤੁਹਾਨੂੰ ਪਿਆਰ ਕਰਦਾ ਹਾਂ', vi: 'Tôi yêu bạn',
    },
    'how are you': {
        fr: 'Comment allez-vous ?', es: '¿Cómo estás?', de: 'Wie geht es Ihnen?',
        hi: 'आप कैसे हैं?', zh: '你好吗?', ja: 'お元気ですか？',
        ko: '어떻게 지내세요?', ru: 'Как дела?', ar: 'كيف حالك؟',
        pt: 'Como vai você?', it: 'Come stai?', bn: 'আপনি কেমন আছেন?',
        te: 'మీరు ఎలా ఉన్నారు?', mr: 'तुम्ही कसे आहात?', ta: 'நீங்கள் எப்படி இருக்கிறீர்கள்?',
        ur: 'آپ کیسے ہیں؟', ml: 'നിങ്ങൾക്ക് എങ്ങനെ ഉണ്ട്?', kn: 'ನೀವು ಹೇಗಿದ್ದೀರಿ?',
        pa: 'ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?', vi: 'Bạn có khỏe không?',
    },
    'what is your name': {
        fr: 'Comment vous appelez-vous ?', es: '¿Cómo te llamas?',
        de: 'Wie heißen Sie?', hi: 'आपका नाम क्या है?',
        zh: '你叫什么名字?', ja: 'お名前は何ですか？',
        ko: '이름이 무엇입니까?', ru: 'Как вас зовут?',
        ar: 'ما اسمك؟', pt: 'Qual é o seu nome?',
        it: 'Come ti chiami?', bn: 'আপনার নাম কী?',
        te: 'మీ పేరు ఏమిటి?', mr: 'तुमचे नाव काय आहे?',
        ta: 'உங்கள் பெயர் என்ன?', ur: 'آپ کا نام کیا ہے؟',
        ml: 'നിങ്ങളുടെ പേര് എന്താണ്?', kn: 'ನಿಮ್ಮ ಹೆಸರೇನು?',
        pa: 'ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ?', vi: 'Tên bạn là gì?',
    },
    'you are welcome': {
        fr: 'De rien', es: 'De nada', de: 'Bitte sehr',
        hi: 'आपका स्वागत है', zh: '不客气', ja: 'どういたしまして',
        ko: '천만에요', ru: 'Пожалуйста', ar: 'على الرحب والسعة',
        pt: 'De nada', it: 'Prego', bn: 'আপনাকে স্বাগতম',
        te: 'స్వాగతం', mr: 'स्वागत आहे', ta: 'உங்களை வரவேற்கிறோம்',
        ur: 'خوش آمدید', ml: 'സ്വാഗതം', kn: 'ಸ್ವಾಗತ',
        pa: 'ਜੀ ਆਇਆਂ ਨੂੰ', vi: 'Không có gì',
    },
};
export const lookupPhrase = (
    text: string,
    src_lang: string,
    tgt_lang: string
): string | null => {
    if (src_lang !== 'en') return null;
    const key = text.trim().toLowerCase().replace(/[?.!,]+$/, '').trim();
    return PHRASEBOOK[key]?.[tgt_lang] ?? null;
};
